FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ./MyWebApp.csproj ./
RUN dotnet restore "MyWebApp.csproj"
COPY . .
RUN dotnet publish ./MyWebApp.csproj -c Release -o /app/

from mcr.microsoft.com/dotnet/sdk:8.0 AS final
WORKDIR /app
ENV DONET_URLS=http://+:5000
COPY --from=build /app .
ENTRYPOINT ["dotnet", "MyWebApp.dll"]