apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-03-02T00:44:45Z"
  labels:
    app: mealie
  name: mealie
  namespace: mealie
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: mealie
  type: LoadBalancer
